### ISSUE TITLE
[Minecraft 1.16.5] - Crash - Naughty Nice Meter interactions with other mods

### ISSUE THREAD

**Issue by DWX12** [jumpcutfindo/happy-holidays#11]
Was testing happyholidays-1.0.0-1.16.5 and the world kept crashing on load. The issue with the mods HappyHolidays is having is all the same. This one is with FeyWild:

Description: Ticking player

java.lang.ClassCastException: com.jumpcutfindo.happyholidays.common.capabilities.christmas.NaughtyNiceMeter cannot be cast to com.feywild.feywild.quest.player.QuestData
	at com.feywild.feywild.quest.player.QuestData.get(QuestData.java:28) ~[feywild:1.16.5-2.0.6] {re:classloading}
	at com.feywild.feywild.EventListener.playerTick(EventListener.java:69) ~[feywild:1.16.5-2.0.6] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_390_EventListener_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[forge:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:ServerPlayNetHandlerPlayerSpeedLimitsMixin,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerPlayNetHandlerKeepAliveMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}

(Not the full crash report, just the first part)

I tested with the following mods and all had the same issue:
Feywild-1.16.5-2.0.6
theoneprobe-1.16-3.1.4
curios-forge-1.16.5-4.0.5.3

Thank you for all of your hard work and effort in creating this mod and hope that the issue can be resolved.

**Comment by jumpcutfindo** [comment]
Hi there, this issue was pointed out previously on the CurseForge forums by a user. I've already implemented a fix in the latest version of [v1.1.2a](https://github.com/jumpcutfindo/happy-holidays/releases/tag/v1.1.2a) which is the recommended version of the mod, do check it out. You can download it from the link I provided or the forums itself! Thanks!

**Comment by DWX12** [comment]
No worries. I know everyone's time is precious (especially this time of year). Thankful for replying and letting people know about the issue. I was able to use the mod without those mods present. Mostly just testing and checking out mods so I'm not really missing out on anything.

Again, thanks for creating this mod and Happy Holidays.
